### ISSUE TITLE
Data Pre-Processing

### ISSUE THREAD

**Issue by L-Scofano** [wei-mao-2019/ContAwareMotionPred#1]
I have found your recent work of great interest and would like to consider it for research purposes. 
Unfortunately, I'm having trouble pre-processing the data you use. 
Could you kindly point out the code you use? 
Additionally, when downloading the GTA dataset, I see two possible folders, the 5FPS and the 30FPS (considerably larger). Do you use both or only one folder?
Lastly, you refer to the temporal Refinement of PROX on the paper. Is there a specific code you use?

Thank you in advance for your response

**Comment by wei-mao-2019** [comment]
Thank you for your interests. The code has been released.
